### PR TITLE
Fix livepatch object name

### PR DESCRIPTION
**Pull request by aliceinwire**

### CODE REVIEW

**Review by gktrk — APPROVED** [review]

**Comment by aliceinwire** [comment]
the name looks changing based on the hook used

**Comment by joe-lawrence** [comment]
> the name looks changing based on the hook used

That is true.  You may also use `kpatch-build -n mod_name` option to specify an exact name if you wish to avoid the "livepatch-", "kpatch-" prefix.

**Comment by aliceinwire** [comment]
defined static livepatch name as "elivepatch-main.ko"

**Comment by aliceinwire** [comment]
tested

**Pull request merged**
